/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JDialog;
import mvc.vista.login.VistaLoginAtencionMesas;
import mvc.vista.login.VistaLoginProcesadoraPedidos;

/**
 *
 * @author Usuario
 */
public class IuStart extends javax.swing.JFrame {

    /**
     * Creates new form IuStart
     */
    public IuStart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInitAppAtencionMesas = new javax.swing.JButton();
        btnInitAppProcesadora = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Obligatorio 2 DDA");

        btnInitAppAtencionMesas.setText("Iniciar App Atencion Mesas");
        btnInitAppAtencionMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitAppAtencionMesasActionPerformed(evt);
            }
        });

        btnInitAppProcesadora.setText("Iniciar Procesadora de Pedidos");
        btnInitAppProcesadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitAppProcesadoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInitAppProcesadora)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInitAppAtencionMesas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnInitAppAtencionMesas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInitAppProcesadora)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInitAppAtencionMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitAppAtencionMesasActionPerformed
        JDialog d = new VistaLoginAtencionMesas(null, false);
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnInitAppAtencionMesasActionPerformed

    private void btnInitAppProcesadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitAppProcesadoraActionPerformed
        JDialog d = new VistaLoginProcesadoraPedidos(null,false);     
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnInitAppProcesadoraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInitAppAtencionMesas;
    private javax.swing.JButton btnInitAppProcesadora;
    // End of variables declaration//GEN-END:variables
}
